/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ntnusubsea.gui;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.KeyStroke;

/**
 * Main frame of the application. Lets the user connect, watch the video stream,
 * observe sensor values, control the lights, open all the extra tools etc.
 * 
 * @author Marius Nonsvik
 */
public class ROVFrame extends javax.swing.JFrame implements Runnable, Observer {

    ImagePanel videoSheet;
    ImagePanel fullscreenVideoSheet;
    private BufferedImage videoImage;
    private Data data;
    private Double setpoint = 0.00;
    private Double previousSetpoint = 0.00;
    private Double redoSetpoint = 0.00;
    private int mode = 0;
    private EchoSounderFrame echoSounder;
    private TCPClient client;
    private IOControlFrame io;
    private final String LIGHTSID = "<Lights>";
    private final String MODEID = "<Mode>";
    private final String SETPOINTID = "<Setpoint>";

    /**
     * Creates new form ROVFrame
     *
     * @param echoSounder Echo sounder frame to show graphs
     * @param data Data containing shared variables
     * @param client TCP client to send commands and receive data
     * @param io I/O frame to control inputs and outputs
     */
    public ROVFrame(EchoSounderFrame echoSounder, Data data, TCPClient client, IOControlFrame io) {
        initComponents();
        this.echoSounder = echoSounder;
        this.data = data;
        this.client = client;
        this.io = io;
        videoSheet = new ImagePanel(cameraPanel.getWidth(), cameraPanel.getHeight());
        videoSheet.setBackground(cameraPanel.getBackground());
        fullscreenVideoSheet = new ImagePanel(cameraPanel1.getWidth(), cameraPanel1.getHeight());
        fullscreenVideoSheet.setBackground(cameraPanel1.getBackground());
        videoSheet.setOpaque(false);
        fullscreenVideoSheet.setOpaque(false);
        cameraPanel.add(videoSheet);
        cameraPanel1.add(fullscreenVideoSheet);
        setpointLabel.setText("Current setpoint: " + setpoint + "m");
        exitFullscreenButton.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "exitFullscreen");
        depthInputTextField.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "sendInput");
        exitFullscreenButton.getActionMap().put("exitFullscreen", exitFullscreenAction);
        depthInputTextField.getActionMap().put("sendInput", sendInputAction);
        
    }

    /**
     * Calls the paintSheet method which updates the diplayed image.
     *
     * @param image The image to be displayed on the GUI
     */
    public void showImage(BufferedImage image) {
        if (fullscreen.isVisible()) {
            fullscreenVideoSheet.setSize(cameraPanel1.getSize());
            fullscreenVideoSheet.paintSheet(ImageUtils.resize(image, fullscreenVideoSheet.getParent().getWidth(), fullscreenVideoSheet.getParent().getHeight()));
        } else {
            videoSheet.paintSheet(ImageUtils.resize(image, videoSheet.getParent().getWidth(), videoSheet.getParent().getHeight()));
            videoSheet.setSize(cameraPanel.getSize());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullscreen = new javax.swing.JFrame();
        cameraPanel1 = new javax.swing.JPanel();
        exitFullscreenButton = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        helpframe = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        cameraPanel = new javax.swing.JPanel();
        fullscreenButton = new javax.swing.JButton();
        controlPanel = new javax.swing.JPanel();
        depthPanel = new javax.swing.JPanel();
        sendButton = new javax.swing.JButton();
        depthInputTextField = new javax.swing.JFormattedTextField();
        depthHeader = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        depthModeButton = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        seafloorModeButton = new javax.swing.JRadioButton();
        setpointLabel = new javax.swing.JLabel();
        lightPanel = new javax.swing.JPanel();
        lightHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lightSwitch = new javax.swing.JToggleButton();
        lightSwitch_lbl = new javax.swing.JLabel();
        emergencyPanel = new javax.swing.JPanel();
        emergencyHeader = new javax.swing.JLabel();
        emergencyStopButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        positionPanel = new javax.swing.JPanel();
        positionHeader = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        headingLabel = new javax.swing.JLabel();
        latitudeLabel = new javax.swing.JLabel();
        longitudeLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        infoPanel = new javax.swing.JPanel();
        pitchLabel = new javax.swing.JLabel();
        seafloorDepthRovLabel = new javax.swing.JLabel();
        rovDepthLabel = new javax.swing.JLabel();
        wingLabel = new javax.swing.JLabel();
        actuatorPanel1 = new javax.swing.JPanel();
        actuatorHeader1 = new javax.swing.JLabel();
        actuatorDutyCycleBar1 = new javax.swing.JProgressBar();
        warningLabel1 = new javax.swing.JLabel();
        actuatorPanel2 = new javax.swing.JPanel();
        actuatorHeader2 = new javax.swing.JLabel();
        actuatorDutyCycleBar2 = new javax.swing.JProgressBar();
        warningLabel2 = new javax.swing.JLabel();
        seafloorDepthBoatLabel = new javax.swing.JLabel();
        rollLabel = new javax.swing.JLabel();
        leakLabel = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemConnect = new javax.swing.JMenuItem();
        jMenuItemDisconnect = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuUndo = new javax.swing.JMenuItem();
        jMenuRedo = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMenuEchosounder = new javax.swing.JMenuItem();
        jMenuIOController = new javax.swing.JMenuItem();
        jMenuOptions = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();

        fullscreen.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        fullscreen.setFocusTraversalPolicyProvider(true);
        fullscreen.setLocationByPlatform(true);
        fullscreen.setUndecorated(true);
        fullscreen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fullscreenKeyPressed(evt);
            }
        });

        cameraPanel1.setBackground(new java.awt.Color(0, 0, 0));
        cameraPanel1.setForeground(new java.awt.Color(255, 255, 255));
        cameraPanel1.setToolTipText("");
        cameraPanel1.setMinimumSize(new java.awt.Dimension(450, 320));
        cameraPanel1.setPreferredSize(new java.awt.Dimension(718, 580));

        exitFullscreenButton.setBackground(new java.awt.Color(0, 0, 0));
        exitFullscreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/exitfullscreenbutton.png"))); // NOI18N
        exitFullscreenButton.setBorder(null);
        exitFullscreenButton.setContentAreaFilled(false);
        exitFullscreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFullscreenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cameraPanel1Layout = new javax.swing.GroupLayout(cameraPanel1);
        cameraPanel1.setLayout(cameraPanel1Layout);
        cameraPanel1Layout.setHorizontalGroup(
            cameraPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cameraPanel1Layout.createSequentialGroup()
                .addGap(0, 708, Short.MAX_VALUE)
                .addComponent(exitFullscreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cameraPanel1Layout.setVerticalGroup(
            cameraPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cameraPanel1Layout.createSequentialGroup()
                .addGap(0, 572, Short.MAX_VALUE)
                .addComponent(exitFullscreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout fullscreenLayout = new javax.swing.GroupLayout(fullscreen.getContentPane());
        fullscreen.getContentPane().setLayout(fullscreenLayout);
        fullscreenLayout.setHorizontalGroup(
            fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cameraPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        fullscreenLayout.setVerticalGroup(
            fullscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cameraPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        helpframe.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        helpframe.setTitle("About");
        helpframe.setType(java.awt.Window.Type.POPUP);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("<html>This code is for the bachelor thesis named \"Towed-ROV\". The purpose is to build a ROV which will be towed behind a surface vessel and act as a multi-sensor platform, were it shall be easy to place new sesnors. There will also be a video stream from the ROV.  <br/><br/>The system consists of a Raspberry Pi on the ROV that is connected to several Arduino microcontrollers that are connected to sensors and and programed with the control system. The external computer which is on the surface vessel is connected to a GPS, echo sounder and the RBPi. It will present and save data in addition to handle user commands.<br/><br/> Created by Marius Nonsvik, Kristian S Homdrom, Morten L Solli and Daniel Reite.<html>");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout helpframeLayout = new javax.swing.GroupLayout(helpframe.getContentPane());
        helpframe.getContentPane().setLayout(helpframeLayout);
        helpframeLayout.setHorizontalGroup(
            helpframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpframeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(helpframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpframeLayout.createSequentialGroup()
                        .addGap(0, 160, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        helpframeLayout.setVerticalGroup(
            helpframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpframeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Towed ROV");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 480));

        background.setBackground(new java.awt.Color(39, 44, 50));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setToolTipText("");
        background.setMinimumSize(new java.awt.Dimension(600, 480));

        cameraPanel.setBackground(new java.awt.Color(39, 44, 50));
        cameraPanel.setForeground(new java.awt.Color(255, 255, 255));
        cameraPanel.setToolTipText("");
        cameraPanel.setAlignmentX(0.8F);
        cameraPanel.setAlignmentY(0.8F);
        cameraPanel.setMinimumSize(new java.awt.Dimension(450, 320));
        cameraPanel.setPreferredSize(new java.awt.Dimension(718, 580));

        fullscreenButton.setBackground(new java.awt.Color(0, 0, 0));
        fullscreenButton.setForeground(new java.awt.Color(255, 255, 255));
        fullscreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/Fullscreenbutton.png"))); // NOI18N
        fullscreenButton.setBorder(null);
        fullscreenButton.setContentAreaFilled(false);
        fullscreenButton.setFocusable(false);
        fullscreenButton.setHideActionText(true);
        fullscreenButton.setName(""); // NOI18N
        fullscreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullscreenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cameraPanelLayout = new javax.swing.GroupLayout(cameraPanel);
        cameraPanel.setLayout(cameraPanelLayout);
        cameraPanelLayout.setHorizontalGroup(
            cameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cameraPanelLayout.createSequentialGroup()
                .addGap(0, 1021, Short.MAX_VALUE)
                .addComponent(fullscreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cameraPanelLayout.setVerticalGroup(
            cameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cameraPanelLayout.createSequentialGroup()
                .addContainerGap(573, Short.MAX_VALUE)
                .addComponent(fullscreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        controlPanel.setBackground(new java.awt.Color(39, 44, 50));
        controlPanel.setMinimumSize(new java.awt.Dimension(150, 140));
        controlPanel.setPreferredSize(new java.awt.Dimension(768, 190));

        depthPanel.setBackground(new java.awt.Color(39, 44, 50));

        sendButton.setBackground(new java.awt.Color(39, 44, 50));
        sendButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sendButton.setText("Send");
        sendButton.setEnabled(false);
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        depthInputTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#.000"))));
        depthInputTextField.setToolTipText("Depth (Meters)");

        depthHeader.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depthHeader.setForeground(new java.awt.Color(255, 255, 255));
        depthHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depthHeader.setText("Depth (meters)");

        jSeparator4.setBackground(new java.awt.Color(67, 72, 83));
        jSeparator4.setForeground(new java.awt.Color(67, 72, 83));

        depthModeButton.setBackground(new java.awt.Color(39, 44, 50));
        buttonGroup1.add(depthModeButton);
        depthModeButton.setForeground(new java.awt.Color(255, 255, 255));
        depthModeButton.setSelected(true);
        depthModeButton.setText("Depth");
        depthModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depthModeButtonActionPerformed(evt);
            }
        });

        jToggleButton1.setText("jToggleButton1");

        seafloorModeButton.setBackground(new java.awt.Color(39, 44, 50));
        buttonGroup1.add(seafloorModeButton);
        seafloorModeButton.setForeground(new java.awt.Color(255, 255, 255));
        seafloorModeButton.setText("Distance from seafloor");
        seafloorModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seafloorModeButtonActionPerformed(evt);
            }
        });

        setpointLabel.setBackground(new java.awt.Color(39, 44, 50));
        setpointLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        setpointLabel.setText("Current setpoint: 100");
        setpointLabel.setToolTipText("");
        setpointLabel.setOpaque(true);

        javax.swing.GroupLayout depthPanelLayout = new javax.swing.GroupLayout(depthPanel);
        depthPanel.setLayout(depthPanelLayout);
        depthPanelLayout.setHorizontalGroup(
            depthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depthHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addGroup(depthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depthPanelLayout.createSequentialGroup()
                        .addComponent(depthInputTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendButton))
                    .addGroup(depthPanelLayout.createSequentialGroup()
                        .addGroup(depthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(depthPanelLayout.createSequentialGroup()
                                .addGroup(depthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(seafloorModeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depthModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton1))
                            .addGroup(depthPanelLayout.createSequentialGroup()
                                .addComponent(setpointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        depthPanelLayout.setVerticalGroup(
            depthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depthPanelLayout.createSequentialGroup()
                .addComponent(depthHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(depthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depthPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(depthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(depthInputTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depthModeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seafloorModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depthPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lightPanel.setBackground(new java.awt.Color(39, 44, 50));

        lightHeader.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lightHeader.setForeground(new java.awt.Color(255, 255, 255));
        lightHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lightHeader.setText("Lights");

        jSeparator1.setBackground(new java.awt.Color(67, 72, 83));
        jSeparator1.setForeground(new java.awt.Color(67, 72, 83));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setBackground(new java.awt.Color(67, 72, 83));
        jSeparator5.setForeground(new java.awt.Color(67, 72, 83));

        lightSwitch.setBackground(new java.awt.Color(39, 44, 50));
        lightSwitch.setForeground(new java.awt.Color(39, 44, 50));
        lightSwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off.gif"))); // NOI18N
        lightSwitch.setBorder(null);
        lightSwitch.setContentAreaFilled(false);
        lightSwitch.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-off.gif"))); // NOI18N
        lightSwitch.setFocusable(false);
        lightSwitch.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/switch-on.gif"))); // NOI18N
        lightSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightSwitchActionPerformed(evt);
            }
        });

        ImageIcon myimage = new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/light-bulb.png"));
        Image img = myimage.getImage();
        Image img2 = img.getScaledInstance(63, 63, Image.SCALE_SMOOTH);
        ImageIcon imgIcon = new ImageIcon(img2);
        lightSwitch_lbl.setIcon(imgIcon);
        lightSwitch_lbl.setMaximumSize(new java.awt.Dimension(63, 100));
        lightSwitch_lbl.setMinimumSize(new java.awt.Dimension(63, 100));

        javax.swing.GroupLayout lightPanelLayout = new javax.swing.GroupLayout(lightPanel);
        lightPanel.setLayout(lightPanelLayout);
        lightPanelLayout.setHorizontalGroup(
            lightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightPanelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(lightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lightHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addGroup(lightPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lightSwitch_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lightSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        lightPanelLayout.setVerticalGroup(
            lightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightPanelLayout.createSequentialGroup()
                .addComponent(lightHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightSwitch_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lightSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        emergencyPanel.setBackground(new java.awt.Color(39, 44, 50));

        emergencyHeader.setBackground(new java.awt.Color(28, 28, 28));
        emergencyHeader.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emergencyHeader.setForeground(new java.awt.Color(255, 255, 255));
        emergencyHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emergencyHeader.setText("Emergency surfacing");

        emergencyStopButton.setBackground(new java.awt.Color(39, 44, 50));
        emergencyStopButton.setForeground(new java.awt.Color(28, 28, 28));
        ImageIcon egm_myimage = new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/emg-stop.gif"));
        Image egm_img = egm_myimage.getImage();
        Image egm_img2 = egm_img.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon egm_imgIcon = new ImageIcon(egm_img2);
        emergencyStopButton.setIcon(egm_imgIcon);
        emergencyStopButton.setBorder(null);
        emergencyStopButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/emg-stop2.gif"))); // NOI18N
        emergencyStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyStopButtonActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(67, 72, 83));
        jSeparator6.setForeground(new java.awt.Color(67, 72, 83));

        javax.swing.GroupLayout emergencyPanelLayout = new javax.swing.GroupLayout(emergencyPanel);
        emergencyPanel.setLayout(emergencyPanelLayout);
        emergencyPanelLayout.setHorizontalGroup(
            emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emergencyHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(jSeparator6)
            .addGroup(emergencyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emergencyStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        emergencyPanelLayout.setVerticalGroup(
            emergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emergencyPanelLayout.createSequentialGroup()
                .addComponent(emergencyHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emergencyStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        positionPanel.setBackground(new java.awt.Color(39, 44, 50));

        positionHeader.setBackground(new java.awt.Color(28, 28, 28));
        positionHeader.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        positionHeader.setForeground(new java.awt.Color(255, 255, 255));
        positionHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionHeader.setText("Position");

        jSeparator7.setBackground(new java.awt.Color(67, 72, 83));
        jSeparator7.setForeground(new java.awt.Color(67, 72, 83));

        headingLabel.setBackground(new java.awt.Color(28, 28, 28));
        headingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("Heading: ");

        latitudeLabel.setBackground(new java.awt.Color(28, 28, 28));
        latitudeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        latitudeLabel.setForeground(new java.awt.Color(255, 255, 255));
        latitudeLabel.setText("Latitude: ");

        longitudeLabel.setBackground(new java.awt.Color(28, 28, 28));
        longitudeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        longitudeLabel.setForeground(new java.awt.Color(255, 255, 255));
        longitudeLabel.setText("Longitude: ");

        javax.swing.GroupLayout positionPanelLayout = new javax.swing.GroupLayout(positionPanel);
        positionPanel.setLayout(positionPanelLayout);
        positionPanelLayout.setHorizontalGroup(
            positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(positionHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator7)
            .addGroup(positionPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(longitudeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(latitudeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        positionPanelLayout.setVerticalGroup(
            positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(positionPanelLayout.createSequentialGroup()
                .addComponent(positionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(latitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(longitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator2.setBackground(new java.awt.Color(67, 72, 83));
        jSeparator2.setForeground(new java.awt.Color(67, 72, 83));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setBackground(new java.awt.Color(67, 72, 83));
        jSeparator3.setForeground(new java.awt.Color(67, 72, 83));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(depthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(emergencyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(positionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(emergencyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(positionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        infoPanel.setBackground(new java.awt.Color(39, 44, 50));

        pitchLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pitchLabel.setForeground(new java.awt.Color(255, 255, 255));
        pitchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pitchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/Box.gif"))); // NOI18N
        pitchLabel.setText("<html>Pitch angle:<br/><br/><center/>10");
        pitchLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        pitchLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        seafloorDepthRovLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seafloorDepthRovLabel.setForeground(new java.awt.Color(255, 255, 255));
        seafloorDepthRovLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seafloorDepthRovLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/Box.gif"))); // NOI18N
        seafloorDepthRovLabel.setText("<html>Depth beneath ROV:<br/><br/><center/>10");
        seafloorDepthRovLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        seafloorDepthRovLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rovDepthLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rovDepthLabel.setForeground(new java.awt.Color(255, 255, 255));
        rovDepthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rovDepthLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/Box.gif"))); // NOI18N
        rovDepthLabel.setText("<html>ROV depth:<br/><br/><center/>10");
        rovDepthLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        rovDepthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        wingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wingLabel.setForeground(new java.awt.Color(255, 255, 255));
        wingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/Box.gif"))); // NOI18N
        wingLabel.setText("<html>Wing angle:<br/><br/><center/>10");
        wingLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        wingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        actuatorPanel1.setBackground(new java.awt.Color(42, 48, 57));
        actuatorPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        actuatorPanel1.setForeground(new java.awt.Color(255, 255, 255));

        actuatorHeader1.setBackground(new java.awt.Color(42, 48, 57));
        actuatorHeader1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        actuatorHeader1.setForeground(new java.awt.Color(255, 255, 255));
        actuatorHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actuatorHeader1.setText("Actuator 1 duty cycle");

        actuatorDutyCycleBar1.setBackground(new java.awt.Color(42, 48, 57));
        actuatorDutyCycleBar1.setForeground(new java.awt.Color(26, 173, 75));
        actuatorDutyCycleBar1.setMaximum(511);
        actuatorDutyCycleBar1.setValue(400);
        actuatorDutyCycleBar1.setBorder(null);
        actuatorDutyCycleBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                actuatorDutyCycleBar1StateChanged(evt);
            }
        });

        warningLabel1.setBackground(new java.awt.Color(42, 48, 57));
        warningLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warningLabel1.setForeground(new java.awt.Color(255, 255, 255));
        warningLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        warningLabel1.setOpaque(true);

        javax.swing.GroupLayout actuatorPanel1Layout = new javax.swing.GroupLayout(actuatorPanel1);
        actuatorPanel1.setLayout(actuatorPanel1Layout);
        actuatorPanel1Layout.setHorizontalGroup(
            actuatorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actuatorHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(warningLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actuatorDutyCycleBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        actuatorPanel1Layout.setVerticalGroup(
            actuatorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actuatorPanel1Layout.createSequentialGroup()
                .addComponent(actuatorHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actuatorDutyCycleBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(warningLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE))
        );

        actuatorPanel2.setBackground(new java.awt.Color(42, 48, 57));
        actuatorPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        actuatorPanel2.setForeground(new java.awt.Color(255, 255, 255));

        actuatorHeader2.setBackground(new java.awt.Color(39, 44, 50));
        actuatorHeader2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        actuatorHeader2.setForeground(new java.awt.Color(255, 255, 255));
        actuatorHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actuatorHeader2.setText("Actuator 2 duty cycle");

        actuatorDutyCycleBar2.setBackground(new java.awt.Color(39, 44, 50));
        actuatorDutyCycleBar2.setForeground(new java.awt.Color(26, 173, 75));
        actuatorDutyCycleBar2.setMaximum(512);
        actuatorDutyCycleBar2.setToolTipText("");
        actuatorDutyCycleBar2.setValue(180);
        actuatorDutyCycleBar2.setBorder(null);
        actuatorDutyCycleBar2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                actuatorDutyCycleBar2StateChanged(evt);
            }
        });

        warningLabel2.setBackground(new java.awt.Color(39, 44, 50));
        warningLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warningLabel2.setForeground(new java.awt.Color(255, 255, 255));
        warningLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout actuatorPanel2Layout = new javax.swing.GroupLayout(actuatorPanel2);
        actuatorPanel2.setLayout(actuatorPanel2Layout);
        actuatorPanel2Layout.setHorizontalGroup(
            actuatorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actuatorHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actuatorDutyCycleBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(warningLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        actuatorPanel2Layout.setVerticalGroup(
            actuatorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actuatorPanel2Layout.createSequentialGroup()
                .addComponent(actuatorHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(actuatorDutyCycleBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(warningLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 9, Short.MAX_VALUE))
        );

        seafloorDepthBoatLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seafloorDepthBoatLabel.setForeground(new java.awt.Color(255, 255, 255));
        seafloorDepthBoatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seafloorDepthBoatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/Box.gif"))); // NOI18N
        seafloorDepthBoatLabel.setText("<html>Depth beneath boat:<br/><br/><center/>10");
        seafloorDepthBoatLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        seafloorDepthBoatLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rollLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rollLabel.setForeground(new java.awt.Color(255, 255, 255));
        rollLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rollLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/Box.gif"))); // NOI18N
        rollLabel.setText("<html>Roll angle:<br/><br/><center/>10");
        rollLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        rollLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rollLabel.setMinimumSize(new java.awt.Dimension(140, 110));

        leakLabel.setBackground(new java.awt.Color(28, 28, 28));
        leakLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leakLabel.setForeground(new java.awt.Color(255, 255, 255));
        leakLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leakLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ntnusubsea/gui/Images/Box.gif"))); // NOI18N
        leakLabel.setText("<html>Leak detection:<br/><br/><center/>No leak detected");
        leakLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 53, 62), 1, true));
        leakLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leakLabel.setPreferredSize(new java.awt.Dimension(170, 100));

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actuatorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actuatorPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wingLabel)
                    .addComponent(pitchLabel)
                    .addComponent(rollLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seafloorDepthRovLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seafloorDepthBoatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rovDepthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(leakLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seafloorDepthBoatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seafloorDepthRovLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pitchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 57, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rovDepthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(leakLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(actuatorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actuatorPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(controlPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                    .addComponent(cameraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(cameraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
            .addComponent(infoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");

        jMenuItemConnect.setText("Connect");
        jMenuItemConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConnectActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemConnect);

        jMenuItemDisconnect.setText("Disconnect");
        jMenuItemDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDisconnectActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemDisconnect);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuUndo.setText("Undo");
        jMenuUndo.setToolTipText("");
        jMenuUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUndoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuUndo);

        jMenuRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuRedo.setText("Redo");
        jMenuRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRedoActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuRedo);

        jMenuBar.add(jMenuEdit);

        jMenuTools.setText("Tools");

        jMenuEchosounder.setText("Echo sounder");
        jMenuEchosounder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEchosounderActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuEchosounder);

        jMenuIOController.setText("I/O Controller");
        jMenuIOController.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIOControllerActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuIOController);

        jMenuOptions.setText("Options");
        jMenuOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOptionsActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuOptions);

        jMenuBar.add(jMenuTools);

        jMenuHelp.setText("Help");
        jMenuHelp.setToolTipText("");

        jMenuAbout.setText("About");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUndoActionPerformed
        // TODO add your handling code here:
        redoSetpoint = setpoint;
        setpoint = previousSetpoint;
        depthInputTextField.setText(setpoint.toString());
        sendButton.doClick();
    }//GEN-LAST:event_jMenuUndoActionPerformed

    private void fullscreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullscreenButtonActionPerformed
        Rectangle maximumWindowBounds = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        int width = (int) maximumWindowBounds.getWidth();
        int height = (int) maximumWindowBounds.getHeight();
        fullscreen.setLocationRelativeTo(this);
        this.setVisible(false);
        fullscreen.setExtendedState(MAXIMIZED_BOTH);
        fullscreen.setUndecorated(true);
        fullscreen.setVisible(true);
        exitFullscreenButton.setBounds(width - exitFullscreenButton.getWidth(), height - exitFullscreenButton.getHeight() - 25, 30, 30);
    }//GEN-LAST:event_fullscreenButtonActionPerformed

    private void exitFullscreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFullscreenButtonActionPerformed
        fullscreen.setVisible(false);
        fullscreen.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_exitFullscreenButtonActionPerformed

    private void fullscreenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullscreenKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ESCAPE) {
            fullscreen.dispose();
        }
        System.out.println(key);
    }//GEN-LAST:event_fullscreenKeyPressed

    private void actuatorDutyCycleBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_actuatorDutyCycleBar1StateChanged
        int actuatorTime1 = actuatorDutyCycleBar1.getValue();
        if (actuatorTime1 <= 255) {
            actuatorDutyCycleBar1.setForeground(new Color(actuatorTime1, 255, 0));
            warningLabel1.setText("");
            warningLabel1.setBackground(new Color(28, 28, 28));
        } else {
            actuatorDutyCycleBar1.setForeground(new Color(255, 255 + (256 - actuatorTime1), 0));
            warningLabel1.setText("Warning!");
            warningLabel1.setBackground(Color.red);
        }
    }//GEN-LAST:event_actuatorDutyCycleBar1StateChanged

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed

        try {
            depthInputTextField.commitEdit();
            double newSetpoint;
            try {
                newSetpoint = (double) depthInputTextField.getValue();
            } catch (ClassCastException ex) {
                Long newSetpointLong = (long) depthInputTextField.getValue();
                newSetpoint = newSetpointLong.doubleValue();
            }
            //newSetpoint = Double.parseDouble(new DecimalFormat("#.000").format(newSetpoint));
            if (newSetpoint <= 50 && newSetpoint >= 0) {
                try {
                    if (true) {
                        client.sendCommand(SETPOINTID + newSetpoint);
                        client.sendCommand(MODEID + mode);
                        //       System.out.println("<Setpoint>" + newSetpoint);
                        //       System.out.println("<Mode>" + mode);
                        setpointLabel.setBackground(new Color(28, 28, 28));
                        previousSetpoint = setpoint;
                        setpoint = newSetpoint;
                        depthInputTextField.setValue(null);
                        setpointLabel.setText("Current setpoint: " + setpoint + "m");
                    } else {
                        depthInputTextField.setValue(null);
                        JOptionPane.showMessageDialog(this,
                                "No connection established.",
                                "Connection error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            } else {
                depthInputTextField.setValue(null);
                JOptionPane.showMessageDialog(this,
                        "Input is invalid. (Max depth 50m)",
                        "Input error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException ex) {
            depthInputTextField.setValue(null);
            System.out.println(ex.getMessage());

        }

    }//GEN-LAST:event_sendButtonActionPerformed

    private void seafloorModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seafloorModeButtonActionPerformed
        mode = 1;
        System.out.println("Mode 1");
    }//GEN-LAST:event_seafloorModeButtonActionPerformed

    private void lightSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightSwitchActionPerformed
        if (lightSwitch.isSelected()) {
            try {
                client.sendCommand(LIGHTSID + 1);
            } catch (IOException ex) {
                Logger.getLogger(ROVFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                client.sendCommand(LIGHTSID + 0);
            } catch (IOException ex) {
                Logger.getLogger(ROVFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lightSwitchActionPerformed

    private void emergencyStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyStopButtonActionPerformed
//        previousSetpoint = setpoint;
//        setpoint = 0.000;
        setpointLabel.setText("Emergency! Setpoint: " + setpoint + "m");
        setpointLabel.setBackground(new Color(255, 0, 0));
        depthModeButton.doClick();
        depthInputTextField.setText("0");
        sendButton.doClick();
    }//GEN-LAST:event_emergencyStopButtonActionPerformed

    private void jMenuItemConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConnectActionPerformed
        String ip = (String) JOptionPane.showInputDialog(this, "Enter IP", "Connection", JOptionPane.PLAIN_MESSAGE, null, null, data.getDefaultIP());
        try {
            client.connect(ip);
            sendButton.setEnabled(true);
            lightSwitch.setEnabled(true);
            emergencyStopButton.setEnabled(true);
            io.enableIO();
            client.sendCommand("<KP>" + data.getKp());
            Thread.sleep(100);
            client.sendCommand("<KI>" + data.getKi());
            Thread.sleep(100);
            client.sendCommand("<KD>" + data.getKd());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Connection failed.",
                    "Conncetion error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemConnectActionPerformed

    private void jMenuItemDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDisconnectActionPerformed
        try {
            client.sendCommand("Quit");
            client.disconnect();
            sendButton.setEnabled(false);
            lightSwitch.setEnabled(false);
            emergencyStopButton.setEnabled(false);
            io.disableIO();
            JOptionPane.showMessageDialog(this,
                    "Successfully disconnected.",
                    "Disconnected",
                    JOptionPane.PLAIN_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Failed to disconnect.",
                    "Disconnect error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemDisconnectActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRedoActionPerformed
        Double tempsetpoint = setpoint;
        setpoint = redoSetpoint;
        depthInputTextField.setText(setpoint.toString());
        sendButton.doClick();
        previousSetpoint = tempsetpoint;
    }//GEN-LAST:event_jMenuRedoActionPerformed


    private void jMenuEchosounderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEchosounderActionPerformed
        if (echoSounder.isVisible()) {
            echoSounder.setVisible(false);
        } else {
            echoSounder.setVisible(true);
        }
    }//GEN-LAST:event_jMenuEchosounderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        helpframe.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        helpframe.setVisible(true);
        helpframe.setSize(helpframe.getPreferredSize());
        helpframe.setLocation(this.getLocation().x, this.getLocation().y);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void actuatorDutyCycleBar2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_actuatorDutyCycleBar2StateChanged
        int actuatorTime2 = actuatorDutyCycleBar2.getValue();
        if (actuatorTime2 <= 255) {
            actuatorDutyCycleBar2.setForeground(new Color(actuatorTime2, 255, 0));
            warningLabel2.setText("");
            warningLabel2.setBackground(new Color(28, 28, 28));
        } else {
            actuatorDutyCycleBar2.setForeground(new Color(255, 255 + (256 - actuatorTime2), 0));
            warningLabel2.setText("Warning!");
            warningLabel2.setBackground(Color.red);
        }
    }//GEN-LAST:event_actuatorDutyCycleBar2StateChanged

    private void jMenuOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOptionsActionPerformed
        OptionsFrame options = new OptionsFrame(data);
        options.setVisible(true);
        options.setLocation(this.getLocation().x, this.getLocation().y);
    }//GEN-LAST:event_jMenuOptionsActionPerformed

    private void depthModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depthModeButtonActionPerformed
        mode = 0;
        System.out.println("Mode 0");
    }//GEN-LAST:event_depthModeButtonActionPerformed

    private void jMenuIOControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIOControllerActionPerformed
        if (io.isVisible()) {
            io.setVisible(false);
        } else {
            io.setVisible(true);
        }
    }//GEN-LAST:event_jMenuIOControllerActionPerformed

    Action exitFullscreenAction = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            exitFullscreenButton.doClick();
        }
    };

    Action sendInputAction = new AbstractAction() {
        public void actionPerformed(ActionEvent e) {
            if (depthInputTextField.isFocusOwner()) {
                sendButton.doClick();
            }

        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar actuatorDutyCycleBar1;
    private javax.swing.JProgressBar actuatorDutyCycleBar2;
    private javax.swing.JLabel actuatorHeader1;
    private javax.swing.JLabel actuatorHeader2;
    private javax.swing.JPanel actuatorPanel1;
    private javax.swing.JPanel actuatorPanel2;
    private javax.swing.JPanel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cameraPanel;
    private javax.swing.JPanel cameraPanel1;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel depthHeader;
    private javax.swing.JFormattedTextField depthInputTextField;
    private javax.swing.JRadioButton depthModeButton;
    private javax.swing.JPanel depthPanel;
    private javax.swing.JLabel emergencyHeader;
    private javax.swing.JPanel emergencyPanel;
    private javax.swing.JButton emergencyStopButton;
    private javax.swing.JButton exitFullscreenButton;
    private javax.swing.JFrame fullscreen;
    private javax.swing.JButton fullscreenButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JFrame helpframe;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuEchosounder;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuIOController;
    private javax.swing.JMenuItem jMenuItemConnect;
    private javax.swing.JMenuItem jMenuItemDisconnect;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuOptions;
    private javax.swing.JMenuItem jMenuRedo;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JMenuItem jMenuUndo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel latitudeLabel;
    private javax.swing.JLabel leakLabel;
    private javax.swing.JLabel lightHeader;
    private javax.swing.JPanel lightPanel;
    private javax.swing.JToggleButton lightSwitch;
    private javax.swing.JLabel lightSwitch_lbl;
    private javax.swing.JLabel longitudeLabel;
    private javax.swing.JLabel pitchLabel;
    private javax.swing.JLabel positionHeader;
    private javax.swing.JPanel positionPanel;
    private javax.swing.JLabel rollLabel;
    private javax.swing.JLabel rovDepthLabel;
    private javax.swing.JLabel seafloorDepthBoatLabel;
    private javax.swing.JLabel seafloorDepthRovLabel;
    private javax.swing.JRadioButton seafloorModeButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel setpointLabel;
    private javax.swing.JLabel warningLabel1;
    private javax.swing.JLabel warningLabel2;
    private javax.swing.JLabel wingLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            videoImage = ImageIO.read(new File("C:\\TowedROV.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(NTNUSubseaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.showImage(videoImage);
        this.setVisible(true); //To change body of generated methods, choose Tools | Templates.

        //
        try {
            //  wingImage = ImageIO.read(new File("Images/rovwing.png"));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        this.showImage(videoImage);

//        try {
//            Thread.sleep(10);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(NTNUSubseaGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    @Override
    public void update(Observable o, Object arg) {
//        actuatorDutyCycleBar1.setValue(data.getBarValue());
        System.out.println(data.getPitchAngle());
        this.showImage(data.getVideoImage());
        headingLabel.setText("Heading: " + data.getHeading());
        longitudeLabel.setText("Longitude: " + data.getLongitude());
        latitudeLabel.setText("Latitude: " + data.getLatitude());
        rovDepthLabel.setText("<html>ROV depth:<br/><br/><center/>" + data.getDepth());
        rollLabel.setText("<html>Roll angle:<br/><br/><center/>" + data.getRollAngle());
        pitchLabel.setText("<html>Pitch angle:<br/><br/><center/>" + data.getPitchAngle());
        wingLabel.setText("<html>Wing angle:<br/><br/><center/>" + data.getWingAngle());
        seafloorDepthBoatLabel.setText("<html>Depth beneath boat:<br/><br/><center/>" + data.getSeafloorBoat());
        seafloorDepthRovLabel.setText("<html>Depth beneath ROV:<br/><br/><center/>" + data.getSeafloorRov());
        if (data.getLeakStatus()) {
            leakLabel.setText("<html>Leak detection:<br/><br/><center/>Leak detected!");
            try {
                leakLabel.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/Box.png"))));
            } catch (IOException ex) {
                Logger.getLogger(ROVFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            leakLabel.setText("<html>Leak detection:<br/><br/><center/>No leak detected");
            try {
                leakLabel.setIcon(new ImageIcon(ImageIO.read(new File("src/ntnusubsea/gui/Images/Box.png"))));
            } catch (IOException ex) {
                Logger.getLogger(ROVFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
